/* =========================================================
   GRUPO BELEGAN — Datos de propiedades (fuente única)
   ---------------------------------------------------------
   Datos reales importados de BBVA Inmuebles (bbvainmuebles.mx)
   el 2026-07-06. Las fotos están descargadas en
   assets/properties/<id>/.

   Esquema de cada propiedad:
     id          {string}  Identificador único y estable (slug). Va en la URL: propiedad.html?id=<id>
     name        {string}  Nombre comercial de la propiedad
     op          {string}  "venta" | "renta"
     tipo        {string}  "Casa" | "Departamento" | "Oficina" | "Local" | "Terreno"
     zona        {string}  Colonia / zona
     ciudad      {string}  Ciudad / municipio
     price       {number}  Precio en MXN (mensual si op = "renta")
     beds        {number}  Recámaras (0 si no aplica)
     baths       {number}  Baños (acepta decimales, ej. 3.5)
     parking     {number}  Cajones de estacionamiento (0 si no aplica)
     m2          {number}  Superficie construida en m²
     m2Terreno   {number}  Superficie de terreno en m² (opcional)
     folio       {string}  Folio del inmueble en BBVA (opcional)
     lat / lng   {number}  Coordenadas GPS (opcional)
     sourceUrl   {string}  Ficha original en bbvainmuebles.mx (opcional)
     pago        {string}  Tipo de pago aceptado (opcional)
     description {string}  Descripción larga
     features    {string[]} Lista de características / amenidades
     photos      {string[]} Fotos. Acepta URL completa (https://...), ruta
                            local (assets/...) o ID de Unsplash.
                            La primera es la portada.
   ========================================================= */
(function () {
  "use strict";

  window.BELEGAN_PROPERTIES = [
    {
      id: "zibata-el-marques-queretaro", name: "Casa Zibatá", op: "venta", tipo: "Casa",
      zona: "Zibatá", ciudad: "El Marqués", price: 5479000,
      beds: 3, baths: 2.5, parking: 2, m2: 160.74,
      m2Terreno: 197.62,
      folio: "538362",
      lat: 20.68248814, lng: -100.3537264,
      sourceUrl: "https://www.bbvainmuebles.mx/inmuebles/zibata-el-marques-queretaro/",
      pago: "Pago con crédito/contado",
      description: "Casa en Zibatá, la comunidad planeada de mayor plusvalía de El Marqués, con campo de golf, parques lineales y comercios a minutos. Tres recámaras, 2.5 baños y cochera para dos autos sobre un terreno de 197.62 m². Propiedad de recuperación bancaria BBVA: acepta crédito hipotecario y el precio es negociable.",
      features: ["Acepta crédito hipotecario", "Precio negociable", "Terreno de 197.62 m²", "Construcción de 160.74 m²", "2 estacionamientos", "Propiedad de recuperación bancaria (BBVA)"],
      photos: [
        "assets/properties/zibata-el-marques-queretaro/01.jpeg",
        "assets/properties/zibata-el-marques-queretaro/02.jpeg",
        "assets/properties/zibata-el-marques-queretaro/03.jpeg",
        "assets/properties/zibata-el-marques-queretaro/04.jpeg",
        "assets/properties/zibata-el-marques-queretaro/05.jpeg",
        "assets/properties/zibata-el-marques-queretaro/06.jpeg",
        "assets/properties/zibata-el-marques-queretaro/07.jpeg",
        "assets/properties/zibata-el-marques-queretaro/08.jpeg",
        "assets/properties/zibata-el-marques-queretaro/09.jpeg",
        "assets/properties/zibata-el-marques-queretaro/10.jpeg",
        "assets/properties/zibata-el-marques-queretaro/11.jpeg",
        "assets/properties/zibata-el-marques-queretaro/12.jpeg",
        "assets/properties/zibata-el-marques-queretaro/13.jpeg",
      ],
    },
    {
      id: "la-vista-residencial-queretaro-queretaro", name: "Casa La Vista Residencial", op: "venta", tipo: "Casa",
      zona: "La Vista Residencial", ciudad: "Querétaro", price: 6230000,
      beds: 3, baths: 3, parking: 2, m2: 208.18,
      m2Terreno: 180,
      folio: "539586",
      lat: 20.641865, lng: -100.36169,
      sourceUrl: "https://www.bbvainmuebles.mx/inmuebles/la-vista-residencial-queretaro-queretaro/",
      pago: "Pago con crédito/contado",
      description: "Casa de 208 m² de construcción en La Vista Residencial, fraccionamiento consolidado al sur de Querétaro con casa club, alberca y vigilancia. Tres recámaras, tres baños completos y dos cajones de estacionamiento. Propiedad de recuperación bancaria BBVA: acepta crédito hipotecario y el precio es negociable.",
      features: ["Acepta crédito hipotecario", "Precio negociable", "Terreno de 180 m²", "Construcción de 208.18 m²", "2 estacionamientos", "Propiedad de recuperación bancaria (BBVA)"],
      photos: [
        "assets/properties/la-vista-residencial-queretaro-queretaro/01.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/02.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/03.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/04.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/05.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/06.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/07.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/08.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/09.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/10.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/11.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/12.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/13.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/14.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/15.jpeg",
        "assets/properties/la-vista-residencial-queretaro-queretaro/16.jpeg",
      ],
    },
    {
      id: "la-canada-el-marques-queretaro", name: "Casa La Cañada", op: "venta", tipo: "Casa",
      zona: "La Cañada", ciudad: "El Marqués", price: 2856000,
      beds: 3, baths: 2.5, parking: 2, m2: 100.63,
      m2Terreno: 111.32,
      folio: "539131",
      lat: 20.598976, lng: -100.306854,
      sourceUrl: "https://www.bbvainmuebles.mx/inmuebles/la-canada-el-marques-queretaro/",
      pago: "Pago con crédito/contado",
      description: "Casa de tres recámaras y 2.5 baños en La Cañada, cabecera de El Marqués, con excelente conexión a la zona industrial y al centro de Querétaro. 100.63 m² de construcción sobre 111.32 m² de terreno. Propiedad de recuperación bancaria BBVA: acepta crédito hipotecario y el precio es negociable.",
      features: ["Acepta crédito hipotecario", "Precio negociable", "Terreno de 111.32 m²", "Construcción de 100.63 m²", "2 estacionamientos", "Propiedad de recuperación bancaria (BBVA)"],
      photos: [
        "assets/properties/la-canada-el-marques-queretaro/01.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/02.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/03.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/04.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/05.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/06.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/07.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/08.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/09.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/10.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/11.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/12.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/13.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/14.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/15.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/16.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/17.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/18.jpeg",
        "assets/properties/la-canada-el-marques-queretaro/19.jpeg",
      ],
    },
    {
      id: "capital-sur-el-marques-queretaro", name: "Casa Capital Sur", op: "venta", tipo: "Casa",
      zona: "Capital Sur", ciudad: "El Marqués", price: 3075000,
      beds: 2, baths: 2.5, parking: 2, m2: 92.69,
      m2Terreno: 99,
      folio: "539603",
      lat: 20.55630139, lng: -100.3120765,
      sourceUrl: "https://www.bbvainmuebles.mx/inmuebles/capital-sur-el-marques-queretaro/",
      pago: "Pago con crédito/contado",
      description: "Casa de dos recámaras y 2.5 baños en Capital Sur, desarrollo con amenidades familiares al sur-oriente de la ciudad. 92.69 m² de construcción, dos estacionamientos, ideal como primera vivienda o inversión. Propiedad de recuperación bancaria BBVA: acepta crédito hipotecario y el precio es negociable.",
      features: ["Acepta crédito hipotecario", "Precio negociable", "Terreno de 99 m²", "Construcción de 92.69 m²", "2 estacionamientos", "Propiedad de recuperación bancaria (BBVA)"],
      photos: [
        "assets/properties/capital-sur-el-marques-queretaro/01.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/02.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/03.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/04.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/05.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/06.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/07.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/08.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/09.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/10.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/11.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/12.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/13.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/14.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/15.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/16.jpeg",
        "assets/properties/capital-sur-el-marques-queretaro/17.jpeg",
      ],
    },
    {
      id: "altos-juriquilla-queretaro-queretaro", name: "Departamento Altos Juriquilla", op: "venta", tipo: "Departamento",
      zona: "Altos Juriquilla", ciudad: "Querétaro", price: 5756000,
      beds: 3, baths: 3.5, parking: 2, m2: 208.5,
      m2Terreno: 140.07,
      folio: "540411",
      lat: 20.685587, lng: -100.46424,
      sourceUrl: "https://www.bbvainmuebles.mx/inmuebles/altos-juriquilla-queretaro-queretaro/",
      pago: "Pago de contado",
      description: "Departamento de 208.5 m² en Altos Juriquilla, con tres recámaras, 3.5 baños y dos cajones de estacionamiento, en una de las zonas de mayor demanda al norte de Querétaro. Propiedad de recuperación bancaria BBVA en venta de contado.",
      features: ["Venta de contado", "Terreno de 140.07 m²", "Construcción de 208.5 m²", "2 estacionamientos", "Propiedad de recuperación bancaria (BBVA)"],
      photos: [
        "assets/properties/altos-juriquilla-queretaro-queretaro/01.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/02.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/03.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/04.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/05.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/06.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/07.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/08.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/09.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/10.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/11.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/12.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/13.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/14.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/15.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/16.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/17.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/18.jpeg",
        "assets/properties/altos-juriquilla-queretaro-queretaro/19.jpeg",
      ],
    },
    {
      id: "adara-lifestyle-el-marques-queretaro", name: "Casa Adara Lifestyle", op: "venta", tipo: "Casa",
      zona: "Adara Lifestyle", ciudad: "El Marqués", price: 3026000,
      beds: 3, baths: 2.5, parking: 2, m2: 111.38,
      m2Terreno: 75,
      folio: "539165",
      lat: 20.590289, lng: -100.319583,
      sourceUrl: "https://www.bbvainmuebles.mx/inmuebles/adara-lifestyle-el-marques-queretaro/",
      pago: "Pago con crédito/contado",
      description: "Casa de tres recámaras y 2.5 baños en Adara Lifestyle, desarrollo moderno de El Marqués con áreas verdes y amenidades. 111.38 m² de construcción y dos estacionamientos. Propiedad de recuperación bancaria BBVA en venta de contado.",
      features: ["Acepta crédito hipotecario", "Terreno de 75 m²", "Construcción de 111.38 m²", "2 estacionamientos", "Propiedad de recuperación bancaria (BBVA)"],
      photos: [
        "assets/properties/adara-lifestyle-el-marques-queretaro/01.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/02.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/03.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/04.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/05.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/06.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/07.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/08.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/09.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/10.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/11.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/12.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/13.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/14.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/15.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/16.jpeg",
        "assets/properties/adara-lifestyle-el-marques-queretaro/17.jpeg",
      ],
    },
    {
      id: "ampliacion-el-refugio-queretaro-queretaro", name: "Casa El Refugio", op: "venta", tipo: "Casa",
      zona: "Ampliación El Refugio", ciudad: "Querétaro", price: 4320675,
      beds: 4, baths: 3, parking: 2, m2: 212.09,
      m2Terreno: 260.54,
      folio: "539382",
      lat: 20.657165, lng: -100.356797,
      sourceUrl: "https://www.bbvainmuebles.mx/inmuebles/ampliacion-el-refugio-queretaro-queretaro/",
      pago: "Pago de contado",
      description: "Amplia casa de cuatro recámaras y tres baños en Ampliación El Refugio, una de las zonas de mayor crecimiento y plusvalía de Querétaro. 212.09 m² de construcción sobre un terreno de 260.54 m². Propiedad de recuperación bancaria BBVA en venta de contado.",
      features: ["Venta de contado", "Terreno de 260.54 m²", "Construcción de 212.09 m²", "2 estacionamientos", "Propiedad de recuperación bancaria (BBVA)"],
      photos: [
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/01.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/02.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/03.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/04.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/05.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/06.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/07.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/08.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/09.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/10.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/11.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/12.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/13.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/14.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/15.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/16.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/17.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/18.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/19.jpeg",
        "assets/properties/ampliacion-el-refugio-queretaro-queretaro/20.jpeg",
      ],
    },
    {
      id: "zizana-el-marques-queretaro", name: "Departamento Zizänä", op: "venta", tipo: "Departamento",
      zona: "Zizänä", ciudad: "El Marqués", price: 2068200,
      beds: 2, baths: 2, parking: 1, m2: 83.871,
      m2Terreno: 105.156,
      folio: "539864",
      lat: 20.654762, lng: -100.303894,
      sourceUrl: "https://www.bbvainmuebles.mx/inmuebles/zizana-el-marques-queretaro/",
      pago: "Pago de contado",
      description: "Departamento de dos recámaras y dos baños en Zizänä, desarrollo con amenidades en El Marqués, cerca del corredor industrial y del aeropuerto. 83.87 m² de construcción y un cajón de estacionamiento. Propiedad de recuperación bancaria BBVA en venta de contado.",
      features: ["Venta de contado", "Terreno de 105.156 m²", "Construcción de 83.871 m²", "1 estacionamiento", "Propiedad de recuperación bancaria (BBVA)"],
      photos: [
        "assets/properties/zizana-el-marques-queretaro/01.jpeg",
        "assets/properties/zizana-el-marques-queretaro/02.jpeg",
        "assets/properties/zizana-el-marques-queretaro/03.jpeg",
        "assets/properties/zizana-el-marques-queretaro/04.jpeg",
        "assets/properties/zizana-el-marques-queretaro/05.jpeg",
        "assets/properties/zizana-el-marques-queretaro/06.jpeg",
        "assets/properties/zizana-el-marques-queretaro/07.jpeg",
        "assets/properties/zizana-el-marques-queretaro/08.jpeg",
        "assets/properties/zizana-el-marques-queretaro/09.jpeg",
        "assets/properties/zizana-el-marques-queretaro/10.jpeg",
        "assets/properties/zizana-el-marques-queretaro/11.jpeg",
        "assets/properties/zizana-el-marques-queretaro/12.jpeg",
        "assets/properties/zizana-el-marques-queretaro/13.jpeg",
        "assets/properties/zizana-el-marques-queretaro/14.jpeg",
        "assets/properties/zizana-el-marques-queretaro/15.jpeg",
        "assets/properties/zizana-el-marques-queretaro/16.jpeg",
      ],
    },
    {
      id: "zizana-el-marques-queretaro-2", name: "Casa Zizänä", op: "venta", tipo: "Casa",
      zona: "Zizänä", ciudad: "El Marqués", price: 3115200,
      beds: 4, baths: 2.5, parking: 2, m2: 122.6,
      m2Terreno: 114,
      folio: "540603",
      lat: 20.651555, lng: -100.305973,
      sourceUrl: "https://www.bbvainmuebles.mx/inmuebles/zizana-el-marques-queretaro-2/",
      pago: "Pago de contado",
      description: "Casa de cuatro recámaras y 2.5 baños en Zizänä, El Marqués, con 122.6 m² de construcción sobre 114 m² de terreno y dos estacionamientos. Propiedad de recuperación bancaria BBVA en venta de contado.",
      features: ["Venta de contado", "Terreno de 114 m²", "Construcción de 122.6 m²", "2 estacionamientos", "Propiedad de recuperación bancaria (BBVA)"],
      photos: [
        "assets/properties/zizana-el-marques-queretaro-2/01.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/02.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/03.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/04.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/05.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/06.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/07.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/08.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/09.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/10.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/11.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/12.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/13.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/14.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/15.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/16.jpeg",
        "assets/properties/zizana-el-marques-queretaro-2/17.jpeg",
      ],
    },
  ];
})();
